version: "3"
services:
  prod:
    build: 
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - 80:80
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 80:80
    command: npm run server