export default Object.freeze({
    ADD_POINT: 'ADD_POINT',
    START_STROKE: 'START_STROKE',
    SET_TIMELINE_STATE: 'SET_TIMELINE_STATE',
    STOP_DRAWING: 'STOP_DRAWING',
    SET_BRUSH_COLOR: 'SET_BRUSH_COLOR',
    SET_AUDIO: 'SET_AUDIO',
    CLEAR_CANVAS: 'CLEAR_CANVAS',
    TOGGLE_TOUCH_MODE: 'TOGGLE_TOUCH_MODE',
});
