export default {
    ADD_POINT: 'ADD_POINT',
    START_STROKE: 'START_STROKE',
    SET_SELECTED_TIMESTAMP: 'SET_SELECTED_TIMESTAMP',
    STOP_DRAWING: 'STOP_DRAWING',
    SET_BRUSH_COLOR: 'SET_BRUSH_COLOR',
};
